### ISSUE TITLE
Use in JupyterLab currently? 

### ISSUE THREAD

**Issue by joelostblom** [python-lsp/docstring-to-markdown#25]
It's really great to see all this progress on a RST docstring converter, thank you for working on it! Is there any way to use this currently for rendering RST docstrings as rich text in jupyterlab's help popups? Or is that something that is planned for the future? I believe I remember seeing you merging in some jupyterlab code previously to allow for extensions to render rich text docstrings.

**Comment by krassowski** [comment]
If we want the markdown to be propagated to frontend forerendering an sanitization, we need to make changes in IPython and Lab: 

1. `append_field` should pass other MIME types down, currently it [ignores anything other than text/plain and text/html](https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/core/oinspect.py#L597-L604)
2. [code formater](https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/core/oinspect.py#L606-L610) should probably return code wrapped in markdown triple backticks
3. append_field` is not called for non-class objects (functions etc) when `detail_level > 0` and source is available, instead source is shown. This appears wrong to me, may need some discussion in IPython.
4. we would need a way to hook our custom formatter in a clean manner from an external package OR get it into IPython core. There are hooks in IPython so maybe could use that.
5. finally we need to ensure that mimetype can be chosen on JupyterLab user (probably in settings).

This sounds pretty much doable in few days of work but also cuts across the stack so help would be needed. Personally, I don't have bandwidth for this and don't use inspector that much (maybe it would change if we implement this).

At some fundamental level I had some pushback in IPython against using markdown as markup format of choice, but I believe the changes above would not be opposed and I would vouch for them.

Some experimental code for testing via monkey-patching:

```python
from IPython import get_ipython
import docstring_to_markdown


ipython = get_ipython()


def markdown_formatter(text):
    try:
        converted = docstring_to_markdown.convert(text)
        return {
            # TODO: adding markdown requires changing `append_field`
            # 'text/markdown': f'{converted}',
            'text/plain': f'{converted}',
            'text/html': f'{converted}'
        }
    except docstring_to_markdown.UnknownFormatError:
        return {
            'text/plain': text,
        }


def our_object_inspect_mime(oname, detail_level=0, omit_sections=()):
    self = ipython

    with self.builtin_trap:
        info = self._object_find(oname)
        if info.found:
            return self.inspector._get_info(
                info.obj,
                oname,
                info=info,
                # Force detail level to zero because otherwise docstring is not shown for most Python objects
                # but source is: TODO This probably needs changing behavour in IPython
                detail_level=0,
                formatter=markdown_formatter,
                omit_sections=omit_sections,
            )
        else:
            raise KeyError(oname)


ipython.object_inspect_mime = our_object_inspect_mime
```

**Comment by krassowski** [comment]
Cross-referencing https://github.com/ipython/ipython/issues/3687 and https://github.com/ipython/ipython/issues/13755

**Comment by joelostblom** [comment]
Thank you so much for taking the time to write this detailed answer! It really helps in understanding what needs to be done to get this working, although I unfortunately don't have bandwidth to take this on either. One effort that is related in terms of the nice rendering aspect is [docrepr](https://github.com/spyder-ide/docrepr) which you might have seen already. There is [a short intro at the end of this article](https://blog.jupyter.org/inspector-jupyterlab-404cce3e1df6) (but there are some issues as well, such as https://github.com/spyder-ide/docrepr/issues/55), maybe there is something in that project that would be helpful here too? 

> Personally, I don't have bandwidth for this and don't use inspector that much (maybe it would change if we implement this).

Out of curiosity, what do you rely on when you are working in JupyterLab and need to read up on a parameter description? Maybe I am missing a more efficient workflow.

**Comment by krassowski** [comment]
Ii knew about spinxify but I haven't seen the blog post, it looks cool! Are there any limitations of docrepr approach that would be solved by passing markdown instead? I guess rendering/theming could be even more consistent and mathajx equations would render properly?

**Comment by joelostblom** [comment]
On a general level I am not sure if there is an advantage of converting rst to markdown versus directly to HTML. As long as the converter accurately covers the full functionality including equations etc. Personally, I have had issues getting the docrepr approach to work reliably in JupyterLab and ideally it would be great if there was a simpler way to render docstrings, maybe even integrated into JupyterLab. I thought they might be more receptive to rich rendering of markdown versus rst, as rst is very python specific.

**Comment by krassowski** [comment]
Recently introduced `Inspector.mime_hooks` should make it much easier (https://github.com/ipython/ipython/pull/14300)

**Comment by krassowski** [comment]
Indeed:

![ipython-docstring-to-markdown](https://github.com/python-lsp/docstring-to-markdown/assets/5832902/16b86a9e-9559-437b-86f7-0e7bdce3259d)

**Comment by krassowski** [comment]
@joelostblom this is now available with: https://github.com/krassowski/ipython-markdown-inspector - can you confirm that it works for you?
