### ISSUE TITLE
Including test file into release tarball

### ISSUE THREAD

**Issue by rhurlin** [python-lsp/docstring-to-markdown#26]
Thanks for the newest release 0.11.

I am the maintainer of the FreeBSD port of python-lsp/docstring-to-markdown [1] and am in the process of updating to version 0.11.

Already with version 0.10 I wondered if there was a reason not to include the file under tests/test_rst.py in the release tarball. The tests run perfectly under FreeBSD and could complement the port well.

[1] https://www.freshports.org/textproc/py-docstring-to-markdown

**Comment by krassowski** [comment]
Thanks! I'm happy to include the tests if it helps downstream. It just happens that they are not picked up because they are one level higher. PRs welcome.

**Comment by rhurlin** [comment]
Sorry, but I have no knowledge with the release process on Github unfortunately.

I had assumed that the full `tests` directory could be easily added to the next release. But apparently it is a bit more difficult? What does it mean that the tests are one level higher? Other files like `Readme.md`, `LICENSE` etc. from the same level as `tests` are also considered, aren't they?

**Comment by hoefling** [comment]
It should be a pretty straightforward task to include the tests in the source dist by specifying them in the sdist manifest, attached a PR that adds this.

**Comment by rhurlin** [comment]
@hoefling @krassowski 
Many thanks! Really appreciated.
