### ISSUE TITLE
Change LGPL license to MIT License.

### ISSUE THREAD

**Issue by npradeep357** [python-lsp/docstring-to-markdown#27]
Is there a specific reason to use LGPL license for this module? All other projects under python-lsp are licensed with MIT and this should also be considered to use the same.

If it is required to use LGPL doesn't the python-lsp-server which is depending on this use the same or re-publish the license?

**Comment by krassowski** [comment]
I don't see why this would be a problem. python-lsp-server does depend on this package but does not bundle it so it does not need to do anything. Even if it bundled this package all it needed to do is to include the licence text. Are you representing a company that has a legal team that highlighted this as a problem in adoption? I am happy to help, let's start by identifying the underlying problem.

**Comment by npradeep357** [comment]
Hi @krassowski, As part of my product I'm bundling python-lsp-server and as a result this component is included in the final distribution. My legal team suggested not to use any of the LGPL licensed components. 
So, I was left with the following options:
I can either take a fork and change the license for my use case. But this involves my team maintaining the updates.
or If there is a possibility of changing the license that would be helpful.

**Comment by npradeep357** [comment]
Or can we make this optional atleast?
