### ISSUE TITLE
Google style docstring support

### ISSUE THREAD

**Issue by staticf0x** [python-lsp/docstring-to-markdown#33]
Hi I wanted to ask if/how the support for Google style docs is planned. I could work on that, but wanted to ask first if you have any implementation in mind. There is another library that can parse Google style docs here: https://github.com/ooreilly/mydocstring but I don't know what's the policy on bringing another dependency into this project. A custom parser would avoid that but on the other hand, we'd need to solve already solved problems. Any help appreciated!

Edit: this is basically for python-lsp-server that I use in sublime text and the docstrings in hover hints are missing formatting and especially newlines.

**Comment by krassowski** [comment]
A pull request (with unit tests) is certainly welcome! We should avoid adding any dependencies. The appeal of this package is that it is easy standalone and plain python which makes it easy to use in python-lsp-server and jedi-language-server. In particular the repository you linked appears to be last updated three years ago and to depend on `mako`, and `docopt` which have further dependencies, some of which would conflict with version pins further in the ecosystem so I would definitely want to avoid it.

**Comment by staticf0x** [comment]
Created PR #34

**Comment by krassowski** [comment]
Thanks again @staticf0x, your PR was included in [v0.13](https://github.com/python-lsp/docstring-to-markdown/releases/tag/v0.13) which is now up on PyPI: https://pypi.org/project/docstring-to-markdown/0.13/

**Comment by staticf0x** [comment]
That was fast! I verified it on another machine, just `pip3 install -U docstring-to-markdown` and python-lsp-server with sublime text works as expected :) Thanks for the fast response!
